import './globals.css'
import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <h1 className="text-3xl">Twitter</h1>
        <nav>
          <ul>
            <li><Link href="/home">Home</Link></li>
            <li><Link href="/notifications">Notifications</Link></li>
            <li><Link href="/messages">Messages</Link></li>
            <li><Link href="/user007">Profile</Link></li>
          </ul>
        </nav>
        <hr className="mb-5" />
        {children}
      </body>
    </html>
  )
}
